#!/bin/sh
#
# SPDX-FileCopyrightText: 2019-2021 Commissariat a l'energie atomique et aux energies alternatives (CEA)
#
# SPDX-License-Identifier: BSD-3-Clause

set -e
export LC_ALL=C

PRE_RELEASE="${1-alpha}"
WORK_DIR="${2-.}"
GIT_EXE="${GIT_EXE-"$(which git 2> /dev/null || true)"}"

if [ git = "${PRE_RELEASE}" ]
then
	PRE_RELEASE=alpha
fi

if [ -x "${GIT_EXE}" ]
then
	cd "${WORK_DIR}"
	GIT_DATE="$("${GIT_EXE}" show -s --format=%ci HEAD | sed 's/ .*//')"
	GIT_SHA1="$("${GIT_EXE}" rev-parse --verify --short=7 HEAD)"
	echo "-${PRE_RELEASE}.${GIT_DATE}.${GIT_SHA1}"
else
	date -u "+-${PRE_RELEASE}.%F"
fi
