#!/bin/bash

WKDIR="$(mktemp -p "${PWD}" -d run-XXXXXXXXXX)"
function finish {
  rm -rf "${WKDIR}"
}
trap finish EXIT

while [ '--runtest-dir-copy-file' = "$1" ]
do
	shift
	cp "$1" "${WKDIR}/"
	shift
done

cd "${WKDIR}"

"$@"
