[default]
extend-ignore-re = [
    '(?Rm)^.*(#|//)\s*typos:disable-line$',
    '(?m)^.*typos:ignore.*$',
    '(#|//)\s*typos:ignore-next-line\n.*',
    '(?s)(#|//)\s*typos:off.*?\n\s*(#|//)\s*typos:on'
]

[default.extend-words]
ND = "ND"
iy = "iy"
iz = "iz"
cpy = "cpy"

[files]
extend-exclude = [
    "vendor/",
    "pdi/docs/_template/",
]
