#!/bin/bash 

# Script that checks the content of orig.
# Compare files *.c and *.c_orig. 
# When there is a difference replace the file *.c int the dest folder with the one in the orig folder.

if [ -d "$1" ] && [ -d "$2" ]; then orig=$1; dest=$2;
else
  echo "Need two valid directories that contain sources files"
  if [[ "${BASH_SOURCE[0]}" != "${0}" ]] # bash is source
  then
    return 1
  else
    exit 1
  fi
fi

for pattern in '*.c' '*.h'
do
	this="$orig""$pattern"
	ls $this > /dev/null 2>&1
	files_found=$?
	
	
	if (( "$files_found" != "2" ))
	then
	  for file in `ls $this`
	  do 
	    copy=$(echo "${file%.c}".orig_c)
	    if [ -s "$copy" ]
	    then
	      replace=$(diff $file $copy | wc -w)
	      #echo "Found $replace words that are different" 
	    fi
	  
	    replace_file=$(echo $file | sed "s#^$orig#$dest#" )
	    if [ -s $replace_file ]
	    then
	      echo "Replacing file $replace_file"
	      cp $file $replace_file
	    fi
	  
	    replace=0
	  done
	fi
done

