#!/bin/bash

# SPDX-FileCopyrightText: 2023 Commissariat a l'energie atomique et aux energies alternatives (CEA)
# SPDX-FileCopyrightText: 2020 Institute of Bioorganic Chemistry Polish Academy of Science (PSNC)
#
# SPDX-License-Identifier: BSD-3-Clause

WKDIR="$(mktemp -p "${PWD}" -d run-XXXXXXXXXX)"
function finish {
  rm -rf "${WKDIR}"
}
trap finish EXIT

while [ '--runtest-dir-copy-file' = "$1" ]
do
	shift
	cp "$1" "${WKDIR}/"
	shift
done

cd "${WKDIR}"

"$@"
