#!/bin/bash

# SPDX-FileCopyrightText: 2019-2023 Commissariat a l'energie atomique et aux energies alternatives (CEA)
#
# SPDX-License-Identifier: BSD-3-Clause

if [ "x-v" = "x${1}" -o "$*" = "" ]
then
	export PDI_VERBOSE_ENV=TRUE
	shift
fi

# this in in bin/, go up one directories
. "$(dirname "$0")/../share/pdi/env.sh"

# run the provided command
exec "$@"
