#!/bin/bash
#=============================================================================
# Copyright (C) 2023 Commissariat a l'energie atomique et aux energies alternatives (CEA)
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * Neither the names of CEA, nor the names of the contributors may be used to
#   endorse or promote products derived from this software without specific
#   prior written  permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#=============================================================================


# retrieve script path from cmake
script_path="$1"

[ -f $script_path ] || exit 1

ERRORS=0

for VAR in CPATH LD_LIBRARY_PATH LIBRARY_PATH PATH PDI_DIR PYTHONPATH
do
	# source in zsh
	ZSH_VAL="$(zsh  -d -f               -c ". "$script_path" ; echo \$${VAR}")"
	BASH_VAL="$(bash --noprofile --norc -c ". "$script_path" ; echo \$${VAR}")"
	if [[ "$ZSH_VAL" != "$BASH_VAL" ]]
	then
		printf "different value for %b:\n* in bash: \`%b'\n*  in zsh: \`%b'\n" "${VAR}" "${ZSH_VAL}" "${BASH_VAL}"  >&2
		((ERRORS++))
	else
		printf "matching value for %b:\n* \`%b'\n" "${VAR}" "${BASH_VAL}"  >&2
	fi
done

exit "${ERRORS}"
