#!/bin/bash
# SPDX-FileCopyrightText: 2023 Commissariat a l'energie atomique et aux energies alternatives (CEA)
#
# SPDX-License-Identifier: BSD-3-Clause


# retrieve script path from cmake
script_path="$1"

[ -f $script_path ] || exit 1

ERRORS=0

for VAR in CPATH LD_LIBRARY_PATH LIBRARY_PATH PATH PDI_DIR PYTHONPATH
do
	# source in zsh
	ZSH_VAL="$(zsh  -d -f               -c ". "$script_path" ; echo \$${VAR}")"
	BASH_VAL="$(bash --noprofile --norc -c ". "$script_path" ; echo \$${VAR}")"
	if [[ "$ZSH_VAL" != "$BASH_VAL" ]]
	then
		printf "different value for %b:\n* in bash: \`%b'\n*  in zsh: \`%b'\n" "${VAR}" "${ZSH_VAL}" "${BASH_VAL}"  >&2
		((ERRORS++))
	else
		printf "matching value for %b:\n* \`%b'\n" "${VAR}" "${BASH_VAL}"  >&2
	fi
done

exit "${ERRORS}"
