#=============================================================================
# Copyright (C) 2024-2026 Commissariat a l'energie atomique et aux energies alternatives (CEA)
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * Neither the names of CEA, nor the names of the contributors may be used to
#   endorse or promote products derived from this software without specific
#   prior written  permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#=============================================================================

name: tests
on:
  push: { branches: [ main, 'v[0-9]+.[0-9]+' ] }
  pull_request:
  workflow_dispatch:
jobs:
  indent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: exec ./bin/test_indent
  first: # do a first run so as not to needlessly use all resources for all to fail
    needs: indent
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout branch
      uses: actions/checkout@v6
      with: { submodules: recursive }
    - name: Test
      uses: ./.github/actions/test/
      with: 
        image: 'ghcr.io/pdidev/spack/latest/clang/mpich/all:v4'
  second: # do a second run at the opposite of the spectrum from the first
    needs: first
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout branch
      uses: actions/checkout@v6
      with: { submodules: recursive }
    - name: Test
      uses: ./.github/actions/test/
      with: 
        image: 'ghcr.io/pdidev/ubuntu/jammy/openmpi/mini:v4'
  spack:
    needs: second
    strategy:
      fail-fast: false
      matrix:
        version:  ['latest', 'oldest']
        compiler: ['gcc', 'clang']
        mpi:      ['openmpi', 'mpich']
        variant:  ['mini', 'all']
        # exclude config already done in first
        exclude: [ { version: latest, compiler: clang, mpi: mpich, variant: all } ]
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout branch
      uses: actions/checkout@v6
      with: { submodules: recursive }
    - name: Test
      uses: ./.github/actions/test/
      with: 
        image: 'ghcr.io/pdidev/spack/${{matrix.version}}/${{matrix.compiler}}/${{matrix.mpi}}/${{matrix.variant}}:v4'
  debuntu:
    needs: second
    strategy:
      fail-fast: false
      matrix:
        base:    ['ubuntu/jammy', 'ubuntu/rolling', 'debian/bookworm', 'debian/unstable']
        mpi:     ['openmpi', 'mpich']
        variant: ['mini', 'all']
        # exclude config already done in second
        exclude: [ { base: 'ubuntu/jammy', mpi: openmpi, variant: mini } ]
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout branch
      uses: actions/checkout@v6
      with: { submodules: recursive }
    - name: Test
      uses: ./.github/actions/test/
      with: 
        image: 'ghcr.io/pdidev/${{matrix.base}}/${{matrix.mpi}}/${{matrix.variant}}:v4'
  macos:
    needs: second
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-15, macos-26]
        cxx_std: ['17']
        build_type: ['Debug']
    runs-on: ${{matrix.os}}
    env:
      MAKEFLAGS: -j4
      CC: clang
      CXX: clang++
      FC: gfortran
      CMAKE_BUILD_TYPE: ${{matrix.build_type}}
      OMPI_MCA_rmaps_base_oversubscribe: 1
      PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe
      PDI_SYSTEM: macos
      PDI_COMPILER: clang
      PDI_MPI: openmpi
      CTEST_DIR: "/tmp/tests_output"
    steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: Install MPI (macOS), Fortran, and doxygen
      run: brew install open-mpi gcc doxygen
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools pyyaml numpy mpi4py
    - name: Set up PDI
      uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Build PDI
      run: bin/build_and_run_all_tests
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v6
      if: ( success() || failure() )  # always run even if the previous step fails
      with:
        report_paths: '/tmp/tests_output/tests_*.xml'
